# Fontes
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Transparência e Blur
# Nota: O desfoque real é controlado pelo seu Picom
background_opacity 0.85
dynamic_background_opacity yes

# Cores Base (Rainy Night)
background         #1a1c23
foreground         #d8dee9
cursor             #88c0d0
selection_background #3b4252
selection_foreground #ffffff

# Cores ANSI (Paleta Azul Polar / Nord-Inspired)

# Black (Asfalto)
color0  #1a1c23
color8  #4c566a

# Red (Ajustado para um tom mais frio/vinho para não quebrar o azul)
color1  #bf616a
color9  #bf616a

# Green (Menta pálido)
color2  #a3be8c
color10 #a3be8c

# Yellow (Azul Areia / Ouro pálido)
color3  #ebcb8b
color11 #ebcb8b

# Blue (Azul Polar - O tom principal do seu tema)
color4  #5e81ac
color12 #81a1c1

# Magenta (Roxo frio)
color5  #b48ead
color13 #b48ead

# Cyan (Azul Glacial - O tom dos seus ícones e destaques)
color6  #88c0d0
color14 #8fbcbb

# White (Neve)
color7  #d8dee9
color15 #eceff4

# Estilo da Janela
window_padding_width 10
confirm_os_window_close 0